version: "3"

services:
   db:
     image: mysql:5.7
     container_name: db
     volumes:
        - db_data:/var/lib/mysql
     restart: always
     env_file: .env
     environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD

   app:
     depends_on:
        - db
     image: wordpress:latest
     container_name: app
     expose:
        - 80
     restart: always
     env_file: .env
     environment:
        VIRTUAL_HOST: $VIRTUAL_HOST
        LETSENCRYPT_HOST: $LETSENCRYPT_HOST
        LETSENCRYPT_EMAIL: $LETSENCRYPT_EMAIL
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: $MYSQL_USER
        WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD

volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
